server:
 context-path: /mail-product
 port: 8082
 
spring:
 datasource:
  url: jdbc:mysql://192.168.0.71:3306/db_product?useSSL=false
  drive-class-name: com.mysql.jdbc.Driver
  username: springboot
  password: springboot
