server:
 port: 8081
 context-path: /study
cupSize: b
age: 18
girl:
 cupSize: c
 age: 18
spring:
 datasource:
  url: jdbc:mysql://192.168.0.71:3306/springboot
  username: spring
  password: springboot
  driver-class-name: com.mysql.jdbc.Driver
  max-idle: 10
  max-wait: 1000
  min-idle: 5
  initial-size: 5
 