server:
 port: 8081
 context-path: /springboot
 
spring:
 datasource:
  url: jdbc:mysql://192.168.0.71:3306/springboot
  driver-class-name: com.mysql.jdbc.Driver
  password: springboot
  username: springboot


 